### ISSUE TITLE
/data file missing

### ISSUE THREAD

**Issue by george-harris** [developmentseed/ml-hv-grid-pub#1]
is it possible to share the final HV maps for each country?

**Comment by wronk** [comment]
Since we put everything in OpenStreetMap, that's the best resource for getting the HV map information. It's maintained/updated there by the community.

I'll update the README to make that clearer

**Comment by george-harris** [comment]
Mark,

Thanks, it’s awesome you’ve put this all on Open Street Map.

I work for a mini-grid developer in East Africa and this type of analysis
is so useful to help us work out where mini-grids might be needed. It’s
really great this type of analysis is being done. Great job to you and your
team.

How far away are you guys from being able to do the same for distribution
grids, say for 11-33 kV lines and substations?

George

**Comment by wronk** [comment]
Hey @george-harris, glad you found it helpful!

Right now, smaller distribution grids might be difficult with our analysis pipeline because the infrastructure (i.e., 11-33kv poles/lines) are hard to see in satellite imagery. It's possible you could do something similar with drone or aerial imagery, but that imagery is more expensive and time-consuming to collect :/

Substations are certainly doable. We just didn't add that component in this iteration of the project :)

What mini-grid developer are you working with?
